import type { JobProvider } from "@/lib/types";

const PROVIDER_NOTE: Record<JobProvider, string> = {
  claude: "Written by Claude, the hosted model.",
  ollama: "Written by a local model running through Ollama.",
};

/**
 * Which model wrote the document you are reading.
 *
 * Not a credit line. A local model and a hosted one do not produce work of the
 * same standard, and the difference is invisible on the page — anyone deciding
 * how far to trust an extraction has to be able to see which one produced it.
 */
export default function ProviderChip({
  provider,
  className = "",
}: {
  provider: JobProvider | null;
  className?: string;
}) {
  if (!provider) return null;
  return (
    <span
      title={PROVIDER_NOTE[provider] ?? undefined}
      className={`shrink-0 rounded-sm border border-rule-soft bg-panel-2 px-1.5 py-0.5 font-mono text-[10px] text-ink-muted ${className}`}
    >
      generated by {provider}
    </span>
  );
}
