"""jobs: track long-running generation out of the request

Revision ID: 172ddf66d061
Revises: 25700522eb07
Create Date: 2026-07-15 21:53:16.817500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # Vector columns in autogenerated DDL
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '172ddf66d061'
down_revision: Union[str, Sequence[str], None] = '25700522eb07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('matter_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_matter_id'), 'jobs', ['matter_id'], unique=False)
    op.create_index('uq_one_live_job_per_matter_kind', 'jobs', ['matter_id', 'kind'], unique=True, postgresql_where=sa.text("status IN ('queued','running')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_one_live_job_per_matter_kind', table_name='jobs', postgresql_where=sa.text("status IN ('queued','running')"))
    op.drop_index(op.f('ix_jobs_matter_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
